language: c

# The apt packages below are needed for sphinx builds, which can no longer
# be installed with sudo apt-get.
addons:
    apt:
        packages:
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        # We run the tests in 'boxed' mode, i.e. one subprocess per test,
        # because there are memory leaks in Astropy that currently cause the
        # memory to go up to levels that cause the tests to be slow.
        - PYTHON_VERSION=3.6
        - SETUP_CMD='test -a "--boxed"'
        - NUMPY_VERSION=stable
        - ASTROPY_VERSION=stable
        - CONDA_DEPENDENCIES='sip<4.19 aplpy pytest-xdist joblib glue-core scipy'
        - CONDA_CHANNELS='astropy glueviz'
        - PIP_DEPENDENCIES='matplotlib<2 Cython https://github.com/radio-astro-tools/pvextractor/archive/master.zip radio_beam https://github.com/astropy/regions/archive/master.zip https://github.com/astropy/reproject/archive/master.zip'
        - SETUP_XVFB=True

matrix:
    include:
        - env: SETUP_CMD='egg_info'

        - env: PYTHON_VERSION=3.5 CONDA_DEPENDENCIES='pytest-xdist' PIP_DEPENDENCIES='radio_beam' NUMPY_VERSION=1.14

        # Do a coverage test in Python 3.
        # make sure *everything* is run for coverage tests
        ## COVERAGE TESTS DISABLED: they don't work any more.  I have found no combination of anything that fixes this.
        - env: SETUP_CMD='test --coverage'
               CONDA_DEPENDENCIES='matplotlib yt bottleneck sip<4.19 aplpy pytest-xdist joblib glue-core scipy'
               PIP_DEPENDENCIES="`echo $PIP_DEPENDENCIES | sed 's/matplotlib<2//'`"

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time.
        # We need to use an old numpy version here as there are warnings in the inherited methods when using newer one
        -  env: SETUP_CMD='build_sphinx -w' NUMPY_VERSION=1.13

        # test python2.7 with recent numpy version
        - env: PYTHON_VERSION=2.7 PYTEST_VERSION="<3.7"
               PIP_DEPENDENCIES='https://github.com/radio-astro-tools/pvextractor/archive/master.zip radio_beam'

        - env: NUMPY_VERSION=1.11 ASTROPY_VERSION=LTS
               CONDA_DEPENDENCIES='matplotlib aplpy bottleneck pytest-xdist'
               PYTEST_VERSION="<3.7"

        # Test with development versions
        - env: PYTHON_VERSION=3.5 NUMPY_VERSION=1.15 ASTROPY_VERSION='development'
               PIP_DEPENDENCIES="`echo $PIP_DEPENDENCIES | sed 's/matplotlib<2//'`"

        - env: ASTROPY_VERSION='development'
               PIP_DEPENDENCIES="`echo $PIP_DEPENDENCIES | sed 's/matplotlib<2//'`"

        - env: CONDA_DEPENDENCIES='matplotlib=3 aplpy yt bottleneck pytest-xdist joblib'
               ASTROPY_VERSION='development'
               PIP_DEPENDENCIES="`echo $PIP_DEPENDENCIES | sed 's/matplotlib<2//'`"


install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh

script:
    - python setup.py $SETUP_CMD

after_success:
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='spectral_cube/tests/coveragerc'; fi
