name: Run tests

on:
  push:
  pull_request:
  schedule:
    # run every Tuesday at 5am UTC
    - cron: '0 5 * * 2'

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: build_docs
        - linux: py38-test
        - linux: py38-test-casa
        - linux: py38-test-noviz
        - linux: py39-test-noviz
        - linux: py39-test-viz-noviz
        - linux: py310-test
        - linux: py310-test-casa
        - linux: py311-test
        - linux: py311-test-dev
        - linux: py311-test-noviz-cov
        - linux: py311-test-noviz-dev
        - linux: py311-test-viz
        - linux: py311-test-viz-noviz-dev
        - linux: py312-test
        - macos: py39-test-noviz
        - windows: py311-test-noviz-dev

